
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  checkout_timeout: 5
  reaping_frequency: 10

development:
  <<: *default
  database: rails
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: rail_learning_test
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: rail_learning_production
  username: postgres
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
