default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: admin
  database: rails

test:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: admin
  database: rail_learning_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>